### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by kindaway** [AnotherGuy7/JoJoStands#1]
Hi, AnotherGuy7. I really like this mod, but i would like to edit some things and nerf someone stand power.  I downloaded 1.73 raw source code, unpacked it and try to compilate... I received 82 errors XD
Can you release compilatable version please?
![issue](https://user-images.githubusercontent.com/63051555/78248650-bb83ad80-74f5-11ea-907d-5194d93ad0ca.PNG)

**Comment by AnotherGuy7** [comment]
This was a long time ago, but you're able to download the code of the mod in the most recent release by going to Releases and downloading the "Source Code (Zip)" option.
