### ISSUE TITLE
Question regarding the status of new features.

### ISSUE THREAD

**Issue by wavpro** [AnotherGuy7/JoJoStands#4]
Hello!
I was wondering if there is a reason why you haven't released the 4 new stands that are available in the dev version?
Is there need for someone that can help with programming, or is it a different issue?

**Comment by AnotherGuy7** [comment]
At the time, we were still preparing for the 1.4 port and the Stand Catch-Up Update, so we couldn't upload half an update. These Stands are out now in the Workshop, which is reaching v2.3.2 right now!
